# Generated by Django 5.2.8 on 2025-11-21 22:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, unique=True, verbose_name='Título')),
                ('fonte_url', models.URLField(max_length=500, verbose_name='URL da Fonte')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('data_publicacao', models.DateTimeField(verbose_name='Data de Publicação')),
                ('data_extracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Extração')),
                ('imagem_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da Imagem de Capa')),
            ],
            options={
                'verbose_name': 'Notícia Diária',
                'verbose_name_plural': 'Notícias Diárias',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_title', models.CharField(max_length=200, verbose_name='Título do Jogo')),
                ('league', models.CharField(max_length=100, verbose_name='Liga/Competição')),
                ('match_date', models.DateTimeField(verbose_name='Data e Hora do Jogo')),
                ('prediction', models.TextField(verbose_name='Prognóstico (Ex: Over 2.5, Casa vence)')),
                ('odd_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Odd (Cotação)')),
                ('resultado_final', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado Final')),
                ('valor_aposta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Aposta (Stake)')),
                ('valor_ganho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Ganho (Lucro)')),
                ('valor_perda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Perda (Prejuízo)')),
                ('link_aposta', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link para Aposta (URL)')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('WIN', 'Ganho'), ('LOSS', 'Perda'), ('VOID', 'Anulada')], default='PENDING', max_length=10, verbose_name='Resultado')),
                ('access_level', models.CharField(choices=[('FREE', 'Grátis'), ('PREMIUM', 'Premium')], default='FREE', max_length=10, verbose_name='Nível de Acesso')),
            ],
            options={
                'verbose_name': 'Dica de Aposta',
                'verbose_name_plural': 'Dicas de Apostas',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_premium_member', models.BooleanField(default=False, verbose_name='Membro Premium')),
                ('premium_expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiração Premium')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Assinatura Premium',
                'verbose_name_plural': 'Assinaturas Premium',
            },
        ),
    ]
