# Generated by Django 5.2.8 on 2025-11-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar esta aposta do site (mas manter no histórico/gráfico).', verbose_name='Aposta Ativa/Visível'),
        ),
    ]
