# Generated by Django 5.2.8 on 2025-11-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0003_remove_tip_prediction_tip_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocaoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Banner')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Curta')),
                ('imagem', models.ImageField(upload_to='promo_banners/', verbose_name='Imagem/Banner')),
                ('link_url', models.URLField(help_text='Link para onde o banner irá direcionar.', max_length=500, verbose_name='URL de Redirecionamento')),
                ('ativo', models.BooleanField(default=True, help_text='Marque para exibir o banner no carrossel.', verbose_name='Banner Ativo')),
                ('ordem', models.IntegerField(default=0, help_text='Defina a ordem de exibição (menor número aparece primeiro).')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner de Promoção',
                'verbose_name_plural': 'Banners de Promoções',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
