# Generated by Django 5.2.8 on 2025-11-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0004_promocaobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocaobanner',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Banner'),
        ),
    ]
