# Generated by Django 5.2.8 on 2025-11-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0005_alter_promocaobanner_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocaobanner',
            name='imagem',
        ),
        migrations.AddField(
            model_name='promocaobanner',
            name='imagem_url',
            field=models.URLField(default=1, help_text='Cole o link da imagem hospedada em um servidor externo (Imgur, Cloud, etc.).', max_length=500, verbose_name='URL Direta da Imagem (Externa)'),
            preserve_default=False,
        ),
    ]
