# Generated by Django 5.2.8 on 2025-11-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0007_alter_noticia_data_publicacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(verbose_name='Data de Publicação'),
        ),
    ]
