# Generated by Django 5.2.8 on 2025-11-26 20:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0008_alter_noticia_data_publicacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocaobanner',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='promocaobanner',
            name='imagem',
            field=models.ImageField(default=1, upload_to='promo_banners/', verbose_name='Imagem/Banner (Upload)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação'),
        ),
    ]
