# Generated by Django 5.2.8 on 2025-12-26 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0009_remove_promocaobanner_imagem_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome do Time')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='Escudo/Logo')),
            ],
            options={
                'verbose_name': 'Time',
                'verbose_name_plural': 'Times',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='tip',
            name='match_title',
        ),
        migrations.AddField(
            model_name='tip',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tips_core.team', verbose_name='Time Visitante'),
        ),
        migrations.AddField(
            model_name='tip',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tips_core.team', verbose_name='Time Casa'),
        ),
    ]
