# Generated by Django 5.2.8 on 2025-12-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0010_team_remove_tip_match_title_tip_away_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='resultado_final',
        ),
        migrations.AddField(
            model_name='tip',
            name='score_away',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gols Visitante'),
        ),
        migrations.AddField(
            model_name='tip',
            name='score_home',
            field=models.IntegerField(blank=True, null=True, verbose_name='Gols Casa'),
        ),
    ]
