# Generated by Django 5.2.8 on 2025-12-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_core', '0011_remove_tip_resultado_final_tip_score_away_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='observation',
            field=models.TextField(blank=True, help_text='Espaço livre para comentar o que aconteceu no jogo.', null=True, verbose_name='Observações/Análise do Resultado'),
        ),
    ]
